spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

sprintlog:
  file-directory: /Users/jangjunseo/Desktop/실무 실습/upload